sudo: required
services:
- docker
cache: false
env:
  - TEST_NAME=sauceChromeTests
  - TEST_NAME=sauceFirefoxTests
  - TEST_NAME=sauceIeTests
  - TEST_NAME=sauceMobileTests

jobs:
  include:
  - stage: install
    script: cd support/acceptance-testing && docker-compose build && docker-compose run acceptance && docker-compose push

before_script:
- cd support/acceptance-testing && docker-compose pull
script:
- docker-compose run acceptance gradle $TEST_NAME
before_deploy:
- docker ps -a
- docker cp `docker ps -aqf "name=_acceptance_"`:/home/groovy/acceptance/build/reports /tmp/
- tar -cvzf "${TEST_NAME}.tar.gz" /tmp/reports
- curl -T "${TEST_NAME}.tar.gz" -uqcifdev:$BINTRAY_API_KEY "https://api.bintray.com/content/qcifdev/redboxsmoketest/testreports/${TEST_NAME}/reports/"

jobs:
  include:
  - stage: deploy
    script: curl -L "https://dl.bintray.com/qcifdev/redboxsmoketest/reports" -o /tmp/reports
    deploy:
      provider: pages
      skip_cleanup: true
      github_token: $GITHUB_TOKEN
      local_dir: /tmp/reports
