sudo: required
services:
  - docker
cache: false
env:
  - TEST_SUITE=sauceChromeTests
  - TEST_SUITE=sauceFirefoxTests
  - TEST_SUITE=sauceIeTests
install:
- docker-compose build
- docker-compose run acceptance
- docker-compose down
before_script:
- cd support/acceptance-testing && docker-compose build
script:
- docker-compose run acceptance gradle $TEST_SUITE
after_success:
- docker ps -a && docker cp `docker ps -aqf "name=_acceptance_"`:/home/groovy/acceptance/build/reports /tmp/
before_deploy:
- tar -cvzf "${TEST_SUITE}.tar.gz" /tmp/reports
- curl -X "DELETE" "https://api.bintray.com/packages/qcifdev/redboxsmoketest/testreports
- curl -T "${TEST_SUITE}.tar.gz" -uqcifdev:$BINTRAY_API_KEY "https://api.bintray.com/content/qcifdev/redboxsmoketest/testreports/${TEST_SUITE}/reports/"

jobs:
  include:
  - stage: deploy
    script: curl -L "https://dl.bintray.com/qcifdev/redboxsmoketest/reports/" -o /tmp/reports
    deploy:
      provider: pages
      skip_cleanup: true
      github_token: $GITHUB_TOKEN
      local_dir: /tmp/reports