sudo: required
services:
- docker
before_install:
- docker-compose rm -f
install:
- docker-compose build
script:
- docker-compose run acceptance gradle test
notifications:
  webhooks:
    urls:
    - http://dev.redboxresearchdata.com.au/hooks/dockerhub?repo=acceptance-testing
    on_success: always
    on_failure: never
    on_cancel: never
    on_error: never
env:
  global:
  - secure: vLECYlXn7Xo04DkRCmG5Ch6DMoKIzjmNQzsE8geWFHmJRJzHutAqv3okSNh1oog0iOwWhUEVD3oBcFe1WIpcaUv+9xIMYoLZTENP7vlgOtsQbF+QzN9VLQDgsT2eGc1eIUUqI+rhpNwYGHlsIW827MWmSeQnliffFu9indjc4gI3f824h8YwMcjyDZ5QzXKELDK2ULWwyTBgRgOXbw+OPA3cB9fItDNH0Dvcbh8pJrqXK4/aYdYuC1JwDYsebwghulTN1wPIO81O0Sb8YOzdwYhLv3Wh38JhhIluSL/rONQcmaQL3mW6cEgalVSgzZBm2AYnmskmhdu3bypjt6NjaylfWoePBDk7ASJ57WDSoqhWi/KBU4NZcJTn63z7ruML6v04Fkinhr2SsndvoEILp+x9NOOeQ7lLIqfWSf4UvuLZ7ovEvvx1LRQttmlLoTX7v7FmqmP58uCJ1Z4nj72mBBX5JAN1Slyi81QXXW1vKyG6WoUGXC9M7LXyPHoM0NGW4rmipwQ+Iq7Tc+uzPAJw2FlG3ePj/Zppl3DxAtil62FybCnmMg+i2waTxT6Qmo+o23uk5i5jUXfLYxs/TCTfUCkj/sodFG4xEgi8OqvKxalhQWgdUXjYtkYSy+JXroSeoc2oegZXwpCy+X1skqdA4WrOLrl+r8619Vl/6MUkHck=
  - SAUCE_USERNAME=qcifdev