sudo: required
services:
- docker
cache: false
before_install:
- docker-compose build
install:
- docker-compose run acceptance gradle test
before_script:
- cd support/acceptance-testing
- docker-compose build
script:
- docker-compose run acceptance gradle test
env:
  global:
  - GEB_BUILD_LOCAL_BASE_URL=http://localhost:9000/redbox/
notifications:
  webhooks:
    urls:
    - http://dev.redboxresearchdata.com.au/hooks/dockerhub
    on_success: always
    on_failure: never
    on_cancel: never
    on_error: never