sudo: required
services:
- docker
before_install:
- docker-compose rm -f
install:
- docker-compose build
script:
- docker-compose run acceptance gradle test
notifications:
  webhooks:
    urls:
    - http://dev.redboxresearchdata.com.au/hooks/dockerhub?repo=acceptance-testing
    on_success: always
    on_failure: never
    on_cancel: never
    on_error: never
env:
  global:
  - secure: vLECYlXn7Xo04DkRCmG5Ch6DMoKIzjmNQzsE8geWFHmJRJzHutAqv3okSNh1oog0iOwWhUEVD3oBcFe1WIpcaUv+9xIMYoLZTENP7vlgOtsQbF+QzN9VLQDgsT2eGc1eIUUqI+rhpNwYGHlsIW827MWmSeQnliffFu9indjc4gI3f824h8YwMcjyDZ5QzXKELDK2ULWwyTBgRgOXbw+OPA3cB9fItDNH0Dvcbh8pJrqXK4/aYdYuC1JwDYsebwghulTN1wPIO81O0Sb8YOzdwYhLv3Wh38JhhIluSL/rONQcmaQL3mW6cEgalVSgzZBm2AYnmskmhdu3bypjt6NjaylfWoePBDk7ASJ57WDSoqhWi/KBU4NZcJTn63z7ruML6v04Fkinhr2SsndvoEILp+x9NOOeQ7lLIqfWSf4UvuLZ7ovEvvx1LRQttmlLoTX7v7FmqmP58uCJ1Z4nj72mBBX5JAN1Slyi81QXXW1vKyG6WoUGXC9M7LXyPHoM0NGW4rmipwQ+Iq7Tc+uzPAJw2FlG3ePj/Zppl3DxAtil62FybCnmMg+i2waTxT6Qmo+o23uk5i5jUXfLYxs/TCTfUCkj/sodFG4xEgi8OqvKxalhQWgdUXjYtkYSy+JXroSeoc2oegZXwpCy+X1skqdA4WrOLrl+r8619Vl/6MUkHck=
  - secure: ZygD+pAQ6QcgEbX4bedHE645S1tB9qCkSu9tYi5mwFT+2Xrhj4p1Q0Lc+tR+14hJH3Cbq17JB35REnJSTzM1IHH7wgQKtgT3kBEPshOa+TYyJPN48AgBB6AgdRn90WefCIlTVvcj/FozMp3iEAN5DjtdnoYHlgLKDRoFPcv9vahB5iaLNKmpNoe4DK050/USi5W9MAGwDo7xW9sXerKhHyfUTvRcXGXnSVGBG+2bmVSxkPiXEzuLPL4E1MUfY2PL6BHtbVGBK/UNJlvcxQQjORwW3zoMcmkCZgW7P1wkt1vMwY7EAuOTEDXg8d65lQC7V8sSWCS85uzMaA/K5UELM43PpSocqLctY+R4/KHKmrrLNYg3vVnNw8PxjnkViUyU0UOxdao/XDgeJ/yBflklaYv5yR3F50RhbVoGFz/CTK3sY8XFAofbLgZZG/KApxv8dOBzONIXEoxxpcQtGsch3bqhJOWYZVG5X2lth0uhpM7UnLsEkA0bt66zo3EVAx1LvsURds/jxubmWQ7k8h//gBWbqv/4L381fAYd+FQr3tEncfBB4505+zVvdRnBynSGG6LNmaIkwQoh98Uyq3I9GeQLJfRNa1xp9FycQ0R/8381TWk+bD6ji4OMYmL3d2qO6WSxnjPVlyw0LKdvdV6clq2ObfCbfHQMHdsV/n5BPSo=
