sudo: required
services:
- docker
before_install:
- docker-compose rm -f
install:
- docker-compose build
script:
- docker-compose run acceptance gradle test
notifications:
  webhooks:
    urls:
    - http://dev.redboxresearchdata.com.au/hooks/dockerhub
    on_success: always
    on_failure: never
    on_cancel: never
    on_error: never