sudo: required
services:
  - docker
cache: false
env:
  - TEST_NAME=sauceChromeTests
  - TEST_NAME=sauceFirefoxTests
  - TEST_NAME=sauceIeTests
  - TEST_NAME=sauceMobileTests
jobs:
  include:
  - stage: install
    script: cd support/acceptance-testing && docker-compose build && docker-compose run acceptance && docker-compose push
  - stage: test
    script: chmod +x ./support/travis/script.sh && ./support/travis/script.sh
  - stage: deploy
    script: curl -L "https://dl.bintray.com/qcifdev/redboxsmoketest/reports" -o /tmp/reports
    deploy:
      script: skip
      provider: pages
      skip_cleanup: true
      github_token: $GITHUB_TOKEN
      local_dir: /tmp/reports