sudo: required
services:
  - docker
before_install:
  - docker-compose rm -f
install:
  - docker-compose build
script:
  - docker-compose run acceptance gradle test
env:
  global:
    - secure: "Vxgyei39WlUVmgxS0EdLzlBW33TkB8SKHHqOd86ZgY2xIK2IF+25DYGsGCy5VubvjnkZqK1YeFoG+s2HiLF4yuSnRcFN+j2+DQ099ZYJfD7eQP/mEjfMG8fHiEnHAoF5/u6v90TaHb9o+KXc3kYMCVGKuoQLwYcOjHUjXz+vm/tGCvmsMZp/uBbzWplJvAE2ogOzN4Ndj1wyTK6DElh6+ie2cyJxjR+Vbks1LWXPef5cWxsvNqqJvZYsbP0JxazwYmSey9sLyubpyKw0JmI02Tllel/RFkGmhy3Y7If7Eny4r0MwjwPLwhKAp3zwL7Blnt9IalXMBf4TDVQ/oIu9jTyu2RCeQOszlBIzLH2UYGeNNV8Fx/LHlz7ProReKnvV3YAnXFkVXsYXTdIzuJo4JEnx9SJsycggeISyTVNllJbLVW36em4AN8rFtslWqbsyKwbi3151yOzqSFhKroqcoqNpW9PxxnoKoVvgDUd/yhsPeUL7u8KS0lv6zbQYl+9ozjJq1MohoveuXbefNWkrVnlgUHdgdXJzr9lge07STFaDhXPQVCvwLhiUrwo46prth3z4EHlgWPybbUmiRSOxNyTZom+yJMKFuh7WSvba/553HynGDVaxSpRft6gIDz6x+9cne7N2agy7dYwaRECf1xV7LOPZkzdSynfh2e9Ivp4="
    - secure: "dnZIHuC5n/yUHASA5jT7gJClBuWF6Zovcb+8qxEHL9TETtedOQviP3tCmSXui6ZAC9thpmj3Ng7CWVL6V9MpCW1dLujRH2TOYsNwrNTnwR3//GlKz9FCw/7w14KTaLtngVKl241v/X6MQhTFx0lWaPQMXHpOkiBBni2McPVrB/jNCHZPzWmv9ESt4kCzuHV2t2Y6CMwjoTrv+AyFlSA0OzLQr/xKwF4diAH1OhVBJFeSsWBv+tvpltWze8YQHx3EMggy4OeHR4bVhXik6kVUZnWD31jrdTGjBCn8HVVHWRbYCydqnTWKXL0JMjI3o/82b9LOCpw5Huw7v/AQaZXKUjUCw2I7VpH9nX1t9GbVdoifIPoalilwqcbYbuubz+nwTIUEykznhV+tF9eqXYuwa5VHM2013fAPV7tZRN1q3E88vMF9tpa9KwNh/CmeU9jos2s+He+kI26QyIx1xqUZzKj2akf7F2UWynr3PvIQdx1D8DbtfZqBl1sJ2rOYKKL9be0SQnuown5kTZTr1MnRxJmAS35LnnzbItkSGIDXY3mskKWODUBCBeeveMLftTrbOU1yhbJv36stD8MpGzoRixeYw1wk1zgXNeSBtkHhI3EIicLQMIF2YliorY+40BWFtInjoTgyrzViXZPGI+81wzmh/1J/tvjk/geuIpT8cto="
notifications:
  webhooks:
    urls:
    - http://dev.redboxresearchdata.com.au/hooks/dockerhub?repo=acceptance-testing
    on_success: always
    on_failure: never
    on_cancel: never
    on_error: never