sudo: required
services:
- docker
cache: false
before_install:
- docker-compose build
install:
- docker-compose run acceptance gradle clean
before_script:
- cd support/acceptance-testing
- docker-compose build
script:
- docker-compose run acceptance gradle test
notifications:
  webhooks:
    urls:
    - http://dev.redboxresearchdata.com.au/hooks/dockerhub
    on_success: always
    on_failure: never
    on_cancel: never
    on_error: never
deploy:
  provider: surge
  project: /tmp/reports
  domain: qcifengineering-acceptance-reports.surge.sh