sudo: required
services:
- docker
before_install:
- docker-compose rm -f
install:
- docker-compose build
script:
- docker-compose run acceptance gradle test
notifications:
  webhooks:
    urls:
    - http://dev.redboxresearchdata.com.au/hooks/dockerhub?repo=acceptance-testing
    on_success: always
    on_failure: never
    on_cancel: never
    on_error: never
env:
  global:
  - SAUCE_ACCESS_KEY=56b45f8e-d291-45e0-91b1-d6068eb409c8
  - SAUCE_USERNAME=qcifdev
  matrix:
  - DUMMY="dummy"