version: '2'
services:
  redbox:
    image: qcifengineering/redbox:latest
    ports:
       - "9000:9000"
  seleniumhub:
    image: selenium/hub:3.4.0
    ports:
      - "4444:4444"
  seleniumnodechrome:
    image: selenium/node-chrome:3.4.0
    environment:
      - HUB_PORT_4444_TCP_ADDR=seleniumhub
      - HUB_PORT_4444_TCP_PORT=4444
    links:
      - seleniumhub:seleniumhub
      - redbox:redbox
  seleniumnodefirefox:
      image: selenium/node-firefox:latest
      environment:
        - HUB_PORT_4444_TCP_ADDR=seleniumhub
        - HUB_PORT_4444_TCP_PORT=4444
      links:
        - seleniumhub:seleniumhub
        - redbox:redbox
  acceptance:
    build: .
    image: qcifengineering/acceptance-testing-redbox:parallel
    depends_on:
      - seleniumnodechrome
      - seleniumnodefirefox
    links:
      - seleniumhub:seleniumhub
      - redbox:redbox
    command: ['gradle', 'test']
    environment:
      - GEB_BUILD_LOCAL_BASE_URL=http://redbox:9000/redbox/
      - SAUCE_ACCESS_KEY
      - SAUCE_USERNAME
      - TRAVIS_BUILD_NUMBER
      - DOCKER_HUB_URL=http://seleniumhub:4444/wd/hub
